"""Explicit producer writes, kept separate from read-only revision calculation."""

import hashlib
from dataclasses import dataclass
from pathlib import Path
import sqlite3

from journey_revisions import calculate_revisions


@dataclass(frozen=True)
class ContentOutputPaths:
    db: Path
    version: Path
    dart: Path | None
    source: Path | None


def validate_output_paths(
    db_path: Path, *, dart_output: Path | None = None,
    source_db: Path | None = None,
) -> ContentOutputPaths:
    """Validate the entire plan without copying, opening SQLite or writing.

    Resolve catches spelling/symlink aliases, including future output paths.
    samefile catches existing hardlinks. This checks the current filesystem;
    it is not a defense against concurrent path replacement (TOCTOU).
    """
    db = db_path.resolve()
    version = db.with_suffix('.version').resolve()
    dart = dart_output.resolve() if dart_output is not None else None
    source = source_db.resolve() if source_db is not None else None
    named = [('DB', db), ('version output', version)]
    if dart is not None:
        named.append(('Dart output', dart))
    if source is not None:
        named.append(('source DB', source))
    for label, path in named:
        if path.exists() and not path.is_file():
            raise ValueError(f'{label} must be a file: {path}')
    for index, (left_label, left) in enumerate(named):
        for right_label, right in named[index + 1:]:
            same = left == right
            if not same:
                try:
                    same = left.samefile(right)
                except FileNotFoundError:
                    # A separate output may legitimately not exist yet.
                    pass
            if same:
                raise ValueError(
                    f'Output plan collision: {left_label} and {right_label} '
                    f'refer to the same file ({left}; {right})'
                )
    return ContentOutputPaths(db, version, dart, source)


def update_journey_revisions(db: sqlite3.Connection) -> int:
    """Update final rows' metadata in the caller's transaction, only if changed."""
    changed = 0
    for row in calculate_revisions(db):
        key, value = "journey_revision_" + row["level"], row["computed"]
        old = db.execute("SELECT value FROM meta WHERE key=?", (key,)).fetchall()
        if old == [(value,)]:
            continue
        if old:
            db.execute("UPDATE meta SET value=? WHERE key=?", (value, key))
        else:
            db.execute("INSERT INTO meta (key,value) VALUES (?,?)", (key, value))
        changed += 1
    return changed


def write_version(
    db_path: Path, *, dart_output: Path | None = None,
    source_db: Path | None = None,
) -> str:
    """Publish markers only after the caller has committed and closed the DB.

    The Dart destination is always explicit. A custom DB cannot accidentally
    overwrite the application's version. Identical marker bytes are not written.
    """
    plan = validate_output_paths(db_path, dart_output=dart_output, source_db=source_db)
    db_path = plan.db.resolve(strict=True)
    if not db_path.is_file():
        raise ValueError("Database path is not a file")
    # Refuse arbitrary/non-SQLite files before publishing either marker.
    db = sqlite3.connect(db_path.as_uri() + "?mode=ro", uri=True)
    try:
        db.execute("SELECT key,value FROM meta LIMIT 1").fetchall()
        if db.execute("PRAGMA integrity_check").fetchone()[0] != "ok":
            raise ValueError("Database integrity check failed")
    finally:
        db.close()
    data = db_path.read_bytes()
    value = f"{hashlib.sha256(data).hexdigest().upper()}:{len(data)}"
    outputs = {plan.version: f"{value}\n"}
    if plan.dart is not None:
        outputs[plan.dart] = (
            "// Generated by content/tools/content_finalization.py. Do not edit.\n"
            f"const String kContentVersion = '{value}';\n"
            f"const int kContentLength = {len(data)};\n"
        )
    for path, text in outputs.items():
        encoded = text.encode("ascii")
        if not path.exists() or path.read_bytes() != encoded:
            path.write_bytes(encoded)
    return value
